### PR TITLE
Move base64 to flamecore

### PR DESCRIPTION
**Pull request by pemensik**
It does not work on EPEL8 with gcc-8.4.1 current way, but works just
fine on Fedora's gcc-11.2.1.  flame/query.cpp uses base64_encode and
thus needs it also in flamecore already.

Without this change building of tests fails with:
``libflamecore.so: undefined reference to `base64_encode[abi:cxx11](unsigned char const*, unsigned int)'``

Sample of [failed build on EPEL8](https://kojipkgs.fedoraproject.org//work/tasks/2277/75892277/build.log).

### CODE REVIEW

**Comment by pemensik** [comment]
Sample of [passed EPEL8 builds](https://koji.fedoraproject.org/koji/taskinfo?taskID=75892662), would remain valid only for 5 days.

**Review by weyrick — APPROVED** [review]
